require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Style/FileName:
  Exclude:
    - "lib/rubocop-eighty-four-codes.rb"
    - "lib/rubocop/eighty-four-codes.rb"

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
