---
AllCops:
  EightyFourCodes:
    Patterns:
      - ".+"

EightyFourCodes/CommandLiteralInjection:
  Description: "Check for Command Injection in `` and %x"
  Enabled: true
  VersionAdded: "0.0.1"

EightyFourCodes/RubyVersionFile:
  Description: "Ensure .ruby-version file use in Gemfile"
  Enabled: true
  VersionAdded: "0.0.1"
